name: DuelEnhancer-OG
author: NotAlexNoyle
description: An extension to Duels by Realizedd made for TrueOG Network
website: https://github.com/true-og/DuelEnhancer-OG/
version: '${version}'
api-version: '${apiVersion}'
main: plugin.DuelEnhancerOG
depend:
  - Utilities-OG
  - Duels-OG
